name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_PORT: 7777

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temporal'   # optional, default is temurin

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build JAR
        run: ./gradlew clean build -x test

      - name: Run SUT (background)
        run: |
          java -jar ./build/libs/app-order.jar &
          echo $! > server.pid

      - name: Wait for SUT to become ready
        run: |
          echo "Waiting for http://localhost:${{ env.APP_PORT }} ..."
          timeout 60 bash -c "until curl -s http://localhost:${{ env.APP_PORT }}/health; do sleep 2; done"

      - name: Execute tests
        run: ./gradlew test

      - name: Stop SUT
        if: always()
        run: |
          kill $(cat server.pid) || echo "process already stopped"

